module.exports = {
  plugins: [
    {
      resolve: "gatsby-theme-auth-app",
      options: {},
    },
  ],
  siteMetadata: {
    title: `Spudnik Dashboard`,
    author: `Reuben Ellis`,
    description: `Welcome to the Spudnik Digital Tools Dashboard!`,
    copyright: `Copyright 2019 SPUDNIK - All rights reserved DISCLAIMER: The values generated by the Farm Analyzer tool are approximations. They are based on available research data and industry expertise. Accuracy of the figures will depend on individual farming systems and conditions. Spudnik, LLC cannot and does not make any guarantee that the values returned will be realized.`,
    loginDesc: "Login",
    isAuthApp: true,
    social: {
      facebook:
        "https://www.facebook.com/Spudnik-Equipment-Company-LLC-123431324379748/",
      twitter: "https://www.twitter.com/",
      github: "https://www.github.com/ethriel3695",
      email: "thedevelopertoolbook@gmail.com",
    },
    externalLinks: [
      { label: "FIR", link: "https://fir.spudnik.com/" },
      { label: "Spudnik Dashboard", link: "https://dashboard.spudnik.com/" },
    ],
  },
}
