export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as ProjectItem } from "./ProjectItem"
export { default as Section } from "./Section"
export { default as Footer } from "./Footer"
export { default as AnimatedWave } from "./AnimatedWave"
